version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Set default reviewers and assignees for pull requests
    reviewers:
      - "rohitjmathew"
    assignees:
      - "rohitjmathew"
    # Only allow patch and minor updates (not major breaking changes)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Labels to apply to pull requests
    labels:
      - "dependencies"
    # Add a commit message prefix
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "rohitjmathew"
    assignees:
      - "rohitjmathew"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"